name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v7

            - name: Welcome message and commands
              run: |
                echo "My first github actions job"
                ls -ltra
                cat test.md
                cat /etc/os-release
            
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover!!!!" >> dragon.txt
            # - name: List files
            #   run: ls

            # - name: Read file
            #   run: cat test.md