name: Generate ASCII Artwork
on: push

jobs:
  generate_ascii_artwork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7

      - name: List files
        run: ls -ltra

      - name: Executing ASCII Script
        run: |
            chmod 777 ./ascii-script.sh
            ./ascii-script.sh
