name: Generate ASCII Artwork
on: push

jobs:
  job_1_list_items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7

      - name: List files
        run: ls -ltra

  job_2_build:
    needs: job_1_list_items
    runs-on: ubuntu-latest
    steps:
      - name: Installing and executing the package
        run: |
          sudo apt-get install cowsay -y
          cowsay -f dragon "Run for cover!!!! I am a DRAGON" >> dragon.txt

  job_3_test:
    needs: [job_2_build]
    runs-on: ubuntu-latest
    steps:
      - name: Test and print
        run: |
          grep -i "dragon" dragon.txt
          cat dragon.txt
