name: Variable & Secrets
on: push

jobs:
  job_1_list_items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7

      - name: List files
        run: ls -ltra

  job_2_build:
    needs: job_1_list_items
    runs-on: ubuntu-latest
    steps:
      - name: Installing and executing the package
        run: |
          sudo apt-get install cowsay -y
          cowsay -f ${{env.CREATURE}} "Run for cover!!!! I am a DRAGON" >> dragon.txt
      - uses: actions/upload-artifact@v7
        with:
          name: dragon
          path: ./dragon.txt

  job_3_test:
    needs: [job_2_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dragon
      - name: Test the file
        run: |
          grep -i "dragon" dragon.txt

  job_4_deploy:
    needs: [job_3_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dragon

      - name: Print the file
        run: cat dragon.txt
